name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: dep
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        go get -u github.com/gordonklaus/ineffassign

    - name: lint
      run: | 
        export PATH=$PATH:$(go env GOPATH)/bin
        ./lint.sh

    - name: test
      run: go test -race
